name: Node.js CI

on:
  push:
    branches:
      - master
      - dev  # Include other branches you want to check
  pull_request:
    branches:
      - main
      - dev  # Include branches you want to enforce tests for pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you're using

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Jest tests
      - name: Run tests
        run: npm test

      # Cache dependencies (optional, but helps to speed up the build)
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
